[workspace]
channels = ["knime", "conda-forge"]
name = "node-env"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test = { cmd = "pytest" }
format = { cmd = "ruff format ." }

[dependencies]
knime-extension = "*"
knime-python-base = "*"
knime-python-versions = "5.8.*"
python = "3.11.*"
ruff = "*"

[pypi-dependencies]
google-api-python-client = "==2.187.0"
google-auth-oauthlib = "==1.2.3"


[feature.build.dependencies]
python = "3.11.*"
knime-extension-bundling = "5.8.*"

[feature.debug.dependencies]
debugpy = "*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "build-python-extension . {{ dest }} --update-sites-version=5.8"}
register-debug-in-knime = { description = "Register the current KNIME extension with a KNIME installation. Usage: 'pixi run register-debug-in-knime' (default locations) or 'pixi run register-debug-in-knime C:/' (search entire C: drive if no executables found). Note windows paths should not end with \\ (backslash)", args = [
                { "arg" = "search_path", "default" = "" }], cmd = "register-debug-in-knime{% if search_path %} --search-path \"{{ search_path }}\"{% endif %}" }


[environments]
build = {features = ["build"], no-default-feature = true}
debug = {features = ["debug"]}
